# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FE\AddAccount\addAccount_UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddAccount(object):
    def setupUi(self, AddAccount):
        AddAccount.setObjectName("AddAccount")
        AddAccount.setEnabled(True)
        AddAccount.resize(600, 400)
        font = QtGui.QFont()
        font.setPointSize(8)
        AddAccount.setFont(font)
        self.plainTextEditAccountText = QtWidgets.QPlainTextEdit(AddAccount)
        self.plainTextEditAccountText.setGeometry(QtCore.QRect(20, 30, 560, 250))
        self.plainTextEditAccountText.setObjectName("plainTextEditAccountText")
        self.label_1 = QtWidgets.QLabel(AddAccount)
        self.label_1.setGeometry(QtCore.QRect(20, 10, 200, 20))
        self.label_1.setTextFormat(QtCore.Qt.PlainText)
        self.label_1.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.label_1.setObjectName("label_1")
        self.buttonAdd = QtWidgets.QPushButton(AddAccount)
        self.buttonAdd.setEnabled(True)
        self.buttonAdd.setGeometry(QtCore.QRect(380, 300, 200, 80))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.buttonAdd.setFont(font)
        self.buttonAdd.setObjectName("buttonAdd")
        self.label_3 = QtWidgets.QLabel(AddAccount)
        self.label_3.setEnabled(True)
        self.label_3.setGeometry(QtCore.QRect(30, 340, 320, 40))
        self.label_3.setMaximumSize(QtCore.QSize(320, 40))
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_3.setObjectName("label_3")
        self.label_2 = QtWidgets.QLabel(AddAccount)
        self.label_2.setGeometry(QtCore.QRect(30, 300, 60, 20))
        self.label_2.setObjectName("label_2")
        self.comboBoxTextFomat = QtWidgets.QComboBox(AddAccount)
        self.comboBoxTextFomat.setEnabled(True)
        self.comboBoxTextFomat.setGeometry(QtCore.QRect(100, 300, 250, 20))
        self.comboBoxTextFomat.setEditable(False)
        self.comboBoxTextFomat.setObjectName("comboBoxTextFomat")
        self.comboBoxTextFomat.addItem("")

        self.retranslateUi(AddAccount)
        QtCore.QMetaObject.connectSlotsByName(AddAccount)

    def retranslateUi(self, AddAccount):
        _translate = QtCore.QCoreApplication.translate
        AddAccount.setWindowTitle(_translate("AddAccount", "Thêm tài khoản"))
        self.label_1.setText(_translate("AddAccount", "Danh sách tài khoản"))
        self.buttonAdd.setText(_translate("AddAccount", "Thêm vào hệ thống"))
        self.label_3.setText(_translate("AddAccount", "Lưu ý: Chọn đúng định dạng trước khi thêm"))
        self.label_2.setText(_translate("AddAccount", "Định dạng:"))
        self.comboBoxTextFomat.setItemText(0, _translate("AddAccount", "UID|Password|Code2FA"))
